# Generated by Django 5.0.7 on 2024-08-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_productindexpage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='title_tag',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_tag',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='game',
            name='keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='game',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='game',
            name='title_tag',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='gameindexpage',
            name='keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='gameindexpage',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='gameindexpage',
            name='title_tag',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='product',
            name='keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='product',
            name='title_tag',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='productindexpage',
            name='keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productindexpage',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='productindexpage',
            name='title_tag',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='review',
            name='keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='review',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='review',
            name='title_tag',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='reviewindexpage',
            name='keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='reviewindexpage',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='reviewindexpage',
            name='title_tag',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
