# Generated by Django 5.0.7 on 2024-08-04 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='linked_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='api.game'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='linked_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='api.product'),
        ),
        migrations.AddField(
            model_name='review',
            name='linked_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='api.game'),
        ),
        migrations.AddField(
            model_name='review',
            name='linked_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='api.product'),
        ),
    ]
