# Generated by Django 5.0.7 on 2024-08-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_blogpost_linked_game_blogpost_linked_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='linked_games',
            field=models.ManyToManyField(blank=True, related_name='products', to='api.game'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('physical', 'Physical Product'), ('digital', 'Digital Product'), ('affiliate', 'Affiliate Product')], default='physical', max_length=10),
        ),
    ]
