# Generated by Django 5.0.7 on 2024-08-04 17:43

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_productcategory_rename_category_articlecategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='reviews', to='api.articlecategory'),
        ),
        migrations.AddField(
            model_name='review',
            name='review_type',
            field=models.CharField(choices=[('game', 'Game'), ('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('monitor', 'Monitor'), ('computer', 'Computer'), ('headphones', 'Headphones'), ('console', 'Console'), ('mobile', 'Mobile'), ('notebook', 'Notebook'), ('microphone', 'Microphone')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ReviewAspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspect', models.CharField(max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('review', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_aspects', to='api.review')),
            ],
            options={
                'unique_together': {('review', 'aspect')},
            },
        ),
    ]
