# Generated by Django 5.0.7 on 2024-08-04 18:26

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_review_review_type_review_score_cena_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('attributes', models.JSONField(default=list)),
            ],
        ),
        migrations.RemoveField(
            model_name='review',
            name='score_cena',
        ),
        migrations.RemoveField(
            model_name='review',
            name='score_chlazeni',
        ),
        migrations.RemoveField(
            model_name='review',
            name='score_design',
        ),
        migrations.RemoveField(
            model_name='review',
            name='score_ergonomie',
        ),
        migrations.RemoveField(
            model_name='review',
            name='score_exkluzivni_hry',
        ),
        migrations.RemoveField(
            model_name='review',
            name='score_fotoaparat',
        ),
        migrations.RemoveField(
            model_name='review',
            name='score_funkce',
        ),
        migrations.RemoveField(
            model_name='review',
            name='score_grafika',
        ),
        migrations.RemoveField(
            model_name='review',
            name='score_hratelnost',
        ),
        migrations.RemoveField(
            model_name='review',
            name='score_konektivita',
        ),
        migrations.RemoveField(
            model_name='review',
            name='score_kvalita',
        ),
        migrations.RemoveField(
            model_name='review',
            name='score_kvalita_displeje',
        ),
        migrations.RemoveField(
            model_name='review',
            name='score_kvalita_materialu',
        ),
        migrations.RemoveField(
            model_name='review',
            name='score_kvalita_obrazu',
        ),
        migrations.RemoveField(
            model_name='review',
            name='score_kvalita_sestaveni',
        ),
        migrations.RemoveField(
            model_name='review',
            name='score_originalita',
        ),
        migrations.RemoveField(
            model_name='review',
            name='score_pohodli',
        ),
        migrations.RemoveField(
            model_name='review',
            name='score_presnost',
        ),
        migrations.RemoveField(
            model_name='review',
            name='score_pribeh',
        ),
        migrations.RemoveField(
            model_name='review',
            name='score_rozhrani',
        ),
        migrations.RemoveField(
            model_name='review',
            name='score_rychlost_odezvy',
        ),
        migrations.RemoveField(
            model_name='review',
            name='score_vydrz_baterie',
        ),
        migrations.RemoveField(
            model_name='review',
            name='score_vykon',
        ),
        migrations.RemoveField(
            model_name='review',
            name='score_zvuk',
        ),
        migrations.CreateModel(
            name='ReviewAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('review', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='api.review')),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='review_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.reviewtype'),
        ),
    ]
