# Generated by Django 5.0.7 on 2024-08-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_reviewtype_remove_review_score_cena_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_type',
            field=models.CharField(choices=[('Game', 'Game'), ('Keyboard', 'Keyboard'), ('Mouse', 'Mouse'), ('Monitor', 'Monitor'), ('Computer', 'Computer'), ('Headphones', 'Headphones'), ('Console', 'Console'), ('Mobile', 'Mobile'), ('Notebook', 'Notebook'), ('Microphone', 'Microphone')], default='Game', max_length=50),
        ),
        migrations.RemoveField(
            model_name='reviewattribute',
            name='description',
        ),
        migrations.DeleteModel(
            name='ReviewType',
        ),
    ]
