# Generated by Django 5.0.7 on 2024-08-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_reviewattribute_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_type',
            field=models.CharField(choices=[('Game', 'Hra'), ('Keyboard', 'Klávesnice'), ('Mouse', 'Myš'), ('Monitor', 'Monitor'), ('Computer', 'Počítač'), ('Headphones', 'Sluchátka'), ('Console', 'Konzole'), ('Mobile', 'Mobil'), ('Notebook', 'Notebook'), ('Microphone', 'Mikrofon')], default='Game', max_length=50),
        ),
    ]
