# Generated by Django 5.0.7 on 2024-08-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_comment_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='dislike_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
