# Generated by Django 5.0.7 on 2024-08-07 16:00

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_review_cons_review_pros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='cons',
        ),
        migrations.RemoveField(
            model_name='review',
            name='pros',
        ),
        migrations.CreateModel(
            name='Con',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('review', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='cons', to='api.review')),
            ],
        ),
        migrations.CreateModel(
            name='Pro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('review', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='pros', to='api.review')),
            ],
        ),
    ]
