# Generated by Django 5.0.7 on 2024-08-07 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_review_cons_remove_review_pros_con_pro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='categories',
        ),
    ]
