# Generated by Django 5.0.7 on 2024-08-08 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_game_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='dislike_count',
        ),
        migrations.RemoveField(
            model_name='game',
            name='like_count',
        ),
    ]
