# Generated by Django 5.0.7 on 2024-08-12 21:02

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_contactmessage_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_us',
            field=wagtail.fields.RichTextField(blank=True, help_text='O nás'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Text ve footeru'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='privacy_policy',
            field=wagtail.fields.RichTextField(blank=True, help_text='Zásady osobních údajů'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='terms_conditions',
            field=wagtail.fields.RichTextField(blank=True, help_text='Obchodní podmínky'),
        ),
    ]
