# Generated by Django 5.0.7 on 2024-08-13 13:58

import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hex_code', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='ClothingSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='platforms',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='api.platform'),
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='api.clothingcolor'),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='api.clothingsize'),
        ),
    ]
