# Generated by Django 5.0.7 on 2024-08-13 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_productvariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='platforms',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
    ]
