# Generated by Django 5.0.7 on 2024-08-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_remove_product_colors_remove_product_platforms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='format',
            field=models.CharField(choices=[('digital', 'Digital'), ('physical', 'Physical')], default='physical', max_length=10),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
