# Generated by Django 5.0.7 on 2024-08-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_remove_product_price_remove_product_product_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aktualita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Text of the update to be displayed', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='If unchecked, this update will not be shown')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
