# Generated by Django 5.0.7 on 2024-08-15 09:55

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_aktualita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktualita',
            name='text',
            field=wagtail.fields.RichTextField(help_text='Text of the update with formatting options'),
        ),
    ]
