# Generated by Django 5.0.7 on 2024-08-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_remove_productvariant_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='active_users_count',
            field=models.IntegerField(default=0),
        ),
    ]
