# Generated by Django 5.0.7 on 2024-08-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_blogpost_active_users_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='week_search',
            field=models.IntegerField(default=0),
        ),
    ]
