# Generated by Django 5.0.7 on 2024-08-17 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_game_week_search'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='week_search',
            new_name='search_week',
        ),
    ]
