# Generated by Django 5.1.4 on 2025-01-10 13:55

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_rename_week_search_game_search_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', 0), ('advertisement', 1)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 1: ('wagtail.blocks.StructBlock', [[]], {})}, default=''),
        ),
        migrations.AlterField(
            model_name='reviewattribute',
            name='text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Popis atributu s možností formátování a přidání obrázků', null=True),
        ),
    ]
