# Generated by Django 5.1.4 on 2025-01-13 21:14

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_alter_blogpost_body_alter_reviewattribute_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-first_published_at']},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', 0), ('advertisement', 1), ('twitter_embed', 3)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 1: ('wagtail.blocks.StructBlock', [[]], {}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': 'Vlož URL příspěvku z Twitteru/X (např. https://x.com/...).', 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('url', 2)]], {})}, default=''),
        ),
    ]
