# Generated by Django 5.1.4 on 2025-01-15 15:51

import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_alter_blogpost_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Název partnera', max_length=255)),
                ('logo', models.ImageField(help_text='Logo partnera', upload_to='partners/logos')),
                ('url', models.URLField(help_text='URL partnera')),
            ],
        ),
        migrations.AddField(
            model_name='homepage',
            name='partners',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='homepages', to='api.partner'),
        ),
    ]
