# Generated by Django 5.1.4 on 2025-01-16 11:34

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_partner_homepage_partners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', 0), ('advertisement', 1), ('table', 2)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 1: ('wagtail.blocks.StructBlock', [[]], {}), 2: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'required': False})}, default=''),
        ),
    ]
