# Generated by Django 5.1.4 on 2025-01-16 11:40

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_alter_blogpost_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', 0), ('advertisement', 1), ('table', 2)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 1: ('wagtail.blocks.StructBlock', [[]], {}), 2: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'table_options': {'minSpareCols': 1, 'minSpareRows': 1, 'startCols': 3, 'startRows': 3}})}, default=''),
        ),
    ]
