# Generated by Django 5.1.4 on 2025-02-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Jméno')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('answers', models.JSONField(verbose_name='Odpovědi v kvízu')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Datum odeslání')),
            ],
            options={
                'verbose_name': 'Soutěžní přihláška',
                'verbose_name_plural': 'Soutěžní přihlášky',
            },
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
