# Generated by Django 5.1.4 on 2025-02-11 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_contestentry_delete_customuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestentry',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Soutěžní přihláška', 'verbose_name_plural': 'Soutěžní přihlášky'},
        ),
    ]
