# Generated by Django 5.1.4 on 2025-02-16 12:04

import api.models
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_alter_contestentry_options'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', 0), ('advertisement', 2), ('table', 3)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 1: ('wagtail.snippets.blocks.SnippetChooserBlock', (api.models.Advertisement,), {}), 2: ('wagtail.blocks.StructBlock', [[('advertisement', 1)]], {}), 3: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'table_options': {'minSpareCols': 1, 'minSpareRows': 1, 'startCols': 3, 'startRows': 3}})}, default=''),
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('click_count', models.IntegerField(default=0)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
            },
        ),
    ]
