  // src/constants/gamingFacts.ts

  const gamingFacts = [
    "Víte, že první videohra vznikla už v roce 1958?",
    "Víte, že Pac-Man byl inspirován pizzou s jedním chybějícím dílkem?",
    "Víte, že nejprodávanější hrou všech dob je Minecraft?",
    "Víte, že prvním názvem pro Mario byla postava Jumpman v Donkey Kongu?",
    "Víte, že konzole PlayStation původně vznikla jako projekt pro Nintendo?",
    "Víte, že Lara Croft měla původně být mužská postava?",
    "Víte, že japonský název pro Pac-Mana je Puck-Man?",
    "Víte, že Tetris byl vyvinut sovětským vědcem Alexejem Pažitnovem?",
    "Víte, že první easter egg ve hře byl v Adventure na Atari?",
    "Víte, že Sonic the Hedgehog byl původně navržen jako králík?",
    "Víte, že první konzole s internetovým připojením byla Sega Dreamcast?",
    "Víte, že ve World of Warcraft existuje panda, která učí hráče bojovým uměním?",
    "Víte, že Doom byl jednou zakázán v Německu kvůli násilí?",
    "Víte, že Microsoft koupil Mojang (tvůrce Minecraftu) za 2,5 miliardy dolarů?",
    "Víte, že první žena v hlavní roli videohry byla Samus Aran v Metroidu?",
    "Víte, že Pokémon znamená 'Pocket Monsters'?",
    "Víte, že ve hře GTA V můžete najít UFO?",
    "Víte, že první konzole s barevnou grafikou byla Fairchild Channel F?",
    "Víte, že Mario byl pojmenován po italském pronajímateli?",
    "Víte, že ve hře Skyrim je kniha s názvem 'Kolik cibule je příliš cibule'?",
    "Víte, že ve hře Halo byl původně místo Master Chiefa obyčejný voják?",
    "Víte, že první 3D hra byla Battlezone z roku 1980?",
    "Víte, že ve hře Red Dead Redemption 2 je realistický růst vlasů?",
    "Víte, že první FPS hra byla Maze War z roku 1973?",
    "Víte, že Nintendo původně vyrábělo karetní hry?",
    "Víte, že ve hře Legend of Zelda je tajný zvuk, pokud zadáte Zeldino jméno jako hráčské jméno?",
    "Víte, že největší mapa ve videohře je ve hře Fuel od Codemasters?",
    "Víte, že první mobilní hra byla Snake na Nokiích?",
    "Víte, že hra Pong byla inspirována stolním tenisem?",
    "Víte, že v GTA V je postava, která paroduje Facebook zakladatele?",
    "Víte, že Luigi je o pár milisekund pomalejší než Mario v Super Mario Bros.?",
    "Víte, že první VR hra byla Virtuality v roce 1991?",
    "Víte, že Pokémon Go byl inspirován aprílovým žertem od Google?",
    "Víte, že v The Witcher 3 má každý NPC svůj denní rozvrh?",
    "Víte, že v Call of Duty Modern Warfare 2 je misi nazvaná 'No Russian'?",
    "Víte, že ve hře Sims můžete zabít Simíka odstraněním schodů z bazénu?",
    "Víte, že Minecraft má více než 100 milionů aktivních hráčů měsíčně?",
    "Víte, že první konzole s CD mechanikou byla Philips CD-i?",
    "Víte, že Half-Life 2 byl jednou z prvních her, které použily ragdoll fyziku?",
    "Víte, že první hra od Rockstar byla Race'n'Chase, která se později stala GTA?",
    "Víte, že první e-sportovní turnaj se konal v roce 1972?",
    "Víte, že Fallout měl původně být licencovaná hra Wasteland?",
    "Víte, že ve Fortnite je tanec 'Floss', který se stal virálním?",
    "Víte, že hra Pong byla původně chybou v softwaru?",
    "Víte, že první herní ovladač byl jednoduchý otočný knoflík?",
    "Víte, že Mario měl původně kladivo místo skoku?",
    "Víte, že ve hře Hitman je tajná mise, kde můžete najít růžového plameňáka?",
    "Víte, že v Cyberpunku 2077 je postava inspirovaná Keanu Reevesem?",
    "Víte, že první ženská hlavní postava byla ve hře Ms. Pac-Man?",
    "Víte, že první videoherní film byl Super Mario Bros. z roku 1993?",
    "Víte, že nejdelší herní série je The Legend of Zelda?",
  ];
  
  export default gamingFacts;
